classes: {
  camino: {
    style.fill: "#fdeacf"
    style.stroke: "#fea01d"
    style.stroke-width: 4
  }
  explorado: { 
    style.fill: "#b9b8b6"
    style.stroke: "#9a9371"
    style.opacity: 0.8
    style.font-color: "#000000"
  }
}

Arad: "Arad\n(h=260)" 
Sibiu: "Sibiu\n(h=175)"
Rimnicu: "Rimnicu Vilcea\n(h=124)"
Craiova: "Craiova\n(h=0)"
Zerind: "Zerind\n(h=283)"

# Oradea : "Oradea\n(h=308)"
Fagaras: "Fagaras\n(h=169)"
Pitesti: "Pitesti\n(h=104)"

Arad.class: camino
Sibiu.class: camino
Rimnicu.class: camino
Craiova.class: camino
Zerind.class: camino
# Oradea.class: explorado
Fagaras.class: explorado
Pitesti.class: explorado

Arad -- Sibiu: 140 km {
  class: camino
}
Arad -- Timisoara: 118 km
Arad -- Zerind: 75 km {
  class: camino
}
Bucharest -- Fagaras: 211 km
Bucharest -- Giurgiu: 90 km
Bucharest -- Pitesti: 101 km
Bucharest -- Urziceni: 85 km
Craiova -- Drobeta: 120 km
Craiova -- Pitesti: 138 km {
   class: explorado
}
Craiova -- Rimnicu: 146 km {
  class: camino
}
Drobeta -- Mehadia: 75 km
Eforie -- Hirsova: 86 km
Fagaras -- Sibiu: 99 km {
   class: explorado
}
Hirsova -- Urziceni: 98 km
Iasi -- Neamt: 87 km
Iasi -- Vaslui: 92 km
Lugoj -- Mehadia: 70 km
Lugoj -- Timisoara: 111 km
Oradea -- Sibiu: 151 km #{
#   class: explorado
#}
Oradea -- Zerind: 71 km #{
#   class: explorado
#}
Pitesti -- Rimnicu: 97 km {
   class: explorado
}
Rimnicu -- Sibiu: 80 km {
  class: camino
}
Urziceni -- Vaslui: 142 km