classes: {
  highlight: {
    style.stroke: red
    style.stroke-width: 4
  }
}

Arad -- Sibiu: 140 km {
  class: highlight
}
Arad -- Timisoara: 118 km
Arad -- Zerind: 75 km {
  class: highlight
}
Bucharest -- Fagaras: 211 km
Bucharest -- Giurgiu: 90 km
Bucharest -- Pitesti: 101 km
Bucharest -- Urziceni: 85 km
Craiova -- Drobeta: 120 km
Craiova -- Pitesti: 138 km
Craiova -- "Rimnicu Vilcea": 146 km {
  class: highlight
}
Drobeta -- Mehadia: 75 km
Eforie -- Hirsova: 86 km
Fagaras -- Sibiu: 99 km
Hirsova -- Urziceni: 98 km
Iasi -- Neamt: 87 km
Iasi -- Vaslui: 92 km
Lugoj -- Mehadia: 70 km
Lugoj -- Timisoara: 111 km
Oradea -- Sibiu: 151 km
Oradea -- Zerind: 71 km
Pitesti -- "Rimnicu Vilcea": 97 km
"Rimnicu Vilcea" -- Sibiu: 80 km {
  class: highlight
}
Urziceni -- Vaslui: 142 km